### ISSUE TITLE
Request failed: GET <target_url> dial tcp:  lookup socket: tool many open files

### ISSUE THREAD

**Issue by okpalindrome** [tomnomnom/fff#6]
After around 100 successful requests, it starts through this error. First ran on WSL, failed and same issue on VM as well. At the end of the subdomain list it starts throwing timeout errors. Any solution or am I missing out anything before starting it.

`cat subdomain_list | fff -d 1 -S -o body_headers`

Thank you in advance!

**Comment by vschwaberow** [comment]
Did you tried to set the ulimit higher?

**Comment by okpalindrome** [comment]
Apologies for not responding quickly. 
This worked on WSL `sudo prlimit --nofile=65536 --pid $$; ulimit -n 65536` 

Thank you!
